### ISSUE TITLE
Create a way to tell if test-system failed.

### ISSUE THREAD

**Issue by tmccombs** [fare/asdf#1]
Right now running test-system doesn't provide a uniform way to tell if a test failed, and instead always returns T.

This is somewhat suprising behaviour. I' would expect the return value of test-system to be a boolean indicating whether or not the tests passed. 

I'm not entirely sure how that would work, but it would make it easier to do things like writing running tests on a system without knowing  anything about the testing framework used.

**Comment by fare** [comment]
1- the bug system for asdf is on launchpad

2- this bug was already discussed on launchpad: https://bugs.launchpad.net/asdf/+bug/479478

3- test-op is already supposed to report failure... by signalling an error as appropriate. If it fails to signal an error when it should, it's a bug in the system, not in ASDF.

4- the resolution was "WON'T FIX".

**Comment by trevor** [comment]
@fare It may be more clear for other users that you prefer Launchpad for bug tracking if the GitHub Issues were disabled for this project. This can be done in Settings -> Options -> Features -> Issues (checkbox)

**Comment by trevor** [comment]
Also you may want to consider mentioning it in the README.md.
